#!/usr/bin/env bash
# ============================================================
# migration-lint.sh — CI guard (Blueprint Section 4 & 32)
#
# Enforces the project-wide convention that EVERY tenant-owned table:
#   1. has a tenant_id column referencing tenancy.tenants
#   2. ENABLE + FORCE ROW LEVEL SECURITY
#   3. has a tenant_isolation policy
#
# A developer adding a new domain table without RLS is the single most
# likely way to introduce a cross-tenant leak. This check fails the build
# if any migration adds a tenant_id column without the matching RLS lines.
#
# Runs in CI on every PR. Platform-level tables (no tenant_id) are exempt
# and must be explicitly allow-listed below.
# ============================================================
set -euo pipefail

MIGRATIONS_DIR="database/migrations"
FAIL=0

# Platform-level tables intentionally without tenant_id / RLS.
ALLOWLIST=(
  "tenancy.tenants"
  "subscription.plans"
  "subscription.features"
  "subscription.plan_features"
  "identity.permissions"
  "compliance.btrc_news"
  "compliance.btrc_news_candidates"
)

for file in "$MIGRATIONS_DIR"/*.sql; do
  # Every CREATE TABLE with a tenant_id column...
  tables_with_tenant=$(grep -oP 'CREATE TABLE \K[a-z_]+\.[a-z_]+' "$file" || true)

  for tbl in $tables_with_tenant; do
    if [[ " ${ALLOWLIST[*]} " == *" $tbl "* ]]; then
      continue
    fi

    block=$(awk "/CREATE TABLE (IF NOT EXISTS )?$tbl /,/;/" "$file")

    if echo "$block" | grep -q "tenant_id"; then
      # A policy may legitimately be declared in a LATER migration (the
      # dedicated 005_rls_policies.sql does exactly this), or generated by
      # a DO-block loop. Search the whole migration set, not just this file.
      if ! grep -rq "CREATE POLICY tenant_isolation ON $tbl" "$MIGRATIONS_DIR"; then
        if ! grep -rqE "FOR t IN|FOR stmt IN" "$MIGRATIONS_DIR"; then
          echo "❌ $tbl has tenant_id but no RLS policy anywhere in $MIGRATIONS_DIR"
          FAIL=1
        fi
      fi
    fi
  done
done

if [[ $FAIL -eq 1 ]]; then
  echo "Migration lint FAILED — tenant-owned tables must enable RLS + tenant_isolation policy."
  exit 1
fi

echo "✅ Migration lint passed — all tenant-owned tables enforce RLS."
